BaseUrl= "http://switchspan.com/"
theme = "casper"
LanguageCode= "en-us"
Title= "Switchspan"
paginate = 5
DisqusShortname = "switchspan"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "Hindsight is an exact science"
  cover = "images/cover.jpg"
  author = "Ken Taylor"
  authorlocation = "Virginia Beach, VA"
  authorwebsite = "http://switchspan.com"
  bio= "I am a software craftsman and lifelong learner"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-41419813-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "switchspan"
  twitterName = "taylorka"
  facebookName = "taylor.kenneth"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false